### ISSUE TITLE
Help to compile

### ISSUE THREAD

**Issue by Disruptor2** [OrangeSpork/EyeLookAdjuster#1]
Hi,
Thank you for this mod. It looks awesome.
I'm a complete noob at working with github projects and I've managed to get nowhere after trying to compile this mod for the last day or so.
Would it be possible to get a link from you of an aleady compiled version of the mod?
Again, thanks for your great work :)

**Comment by OrangeSpork** [comment]
All github projects have a release section which has built versions. It's over on the right or directly here: https://github.com/OrangeSpork/EyeLookAdjuster/releases
